server:
  port: 7000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33006/ad_data
    username: root
    password: "root"
    tomcat:
      max-active: 4
      min-idle: 2
      inital-size: 2
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/,http://server3:8002/eureka/